CREATE TABLE t5(
   upload_timestamp TEXT,
   time_delta REAL,
   lift_number INTEGER,
   state  INTEGER,
   state_delta INTEGER,
   RBF INTEGER,
   REA INTEGER,
   RIB INTEGER,
   RSM INTEGER,
   LETO INTEGER,
   LETS INTEGER,
   LETO2 INTEGER,
   LETS2 INTEGER,
   OUT1 INTEGER,
   OUT2 INTEGER,
   OUT3 INTEGER,
   OUT4 INTEGER,
   RBF_delta INTEGER,
   REA_delta INTEGER,
   RIB_delta INTEGER,
   RSM_delta INTEGER,
   LETO_delta INTEGER,
   LETS_delta INTEGER,
   LETO2_delta INTEGER,
   LETS2_delta INTEGER,
   OUT1_delta INTEGER,
   OUT2_delta INTEGER,
   OUT3_delta INTEGER,
   OUT4_delta INTEGER,
   FLOORNO INTEGER,
   RESET INTEGER
   );
   
.mode csv
.import outputt5.csv t5
